import { MODULE } from './constants';

const SET_FIELD_VALUE = `${MODULE}/SET_FIELD_VALUE`;
const SET_STEP_VALIDITY = `${MODULE}/SET_STEP_VALIDITY`;
const SET_STEP_VALUES = `${MODULE}/SET_STEP_VALUES`;
const SET_STEP_CONFIRMED = `${MODULE}/SET_STEP_CONFIRMED`;
const SET_STEP_ERROR = `${MODULE}/SET_STEP_ERROR`;
const SET_FORM_SUBMIT_VALUES = `${MODULE}/SET_FORM_SUBMIT_VALUES`;
const SET_FORM_SUBMIT_RESULT = `${MODULE}/SET_FORM_SUBMIT_RESULT`;
const SET_FORM_SUBMIT_ERROR = `${MODULE}/SET_FORM_SUBMIT_ERROR`;
const SET_FORM_SUBMITTING = `${MODULE}/SET_FORM_SUBMITTING`;

export default {
  SET_FIELD_VALUE,
  SET_STEP_VALIDITY,
  SET_STEP_VALUES,
  SET_STEP_CONFIRMED,
  SET_STEP_ERROR,
  SET_FORM_SUBMIT_VALUES,
  SET_FORM_SUBMIT_RESULT,
  SET_FORM_SUBMIT_ERROR,
  SET_FORM_SUBMITTING,
};
